### ISSUE TITLE
Target custom golang directory

### ISSUE THREAD

**Issue by guillermo-menjivar** [actions-contrib/golangci-lint#4]
Hello I am trying to configure golangci-lint action against my repo. I have code that is nested under my monorepo. <root>/some-dir/<my-golang-code>
When I run the actions the containers errors with message "no go files found". What is the property to add to my yaml definition to inform golangci-lint action where to look for my code

**Comment by syntaqx** [comment]
Can you give me an example of which files are nested in the directory? That will help me debug further.

**Comment by syntaqx** [comment]
You should be able to change the `arg: run` to run against your preferred directory (by default it uses `./...` resolution), so something like `arg: run /some/other/folder`.

Closing as I believe this addresses your concern, will reopen if I'm incorrect
